spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: hye2021
    password: hye2021
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:${user.home}/myBlogImages/images/

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie
